INSERT INTO notes (title, content, user_id) VALUES
    ('Morning Stretch', 'Started the day with a big stretch and a loud yawn. Feeling refreshed!', 999),
    ('Window Watching', 'Spent an hour watching birds outside the window. Dreaming of catching one someday.', 999),
    ('Nap Time', 'Found a sunny spot on the couch and took a glorious two-hour nap.', 999),
    ('Play Session', 'Chased the red dot from the laser pointer all over the living room. Still couldn’t catch it!', 999),
    ('Snack Break', 'Stole a bite of tuna from the counter when nobody was looking. Delicious!', 999),
    ('Garden Adventure', 'Escaped to the garden and climbed the tallest tree. Felt like a jungle cat!', 999),
    ('Evening Zoomies', 'Ran in circles around the house at full speed. Humans looked confused.', 999),
    ('Cuddles', 'Snuggled up with the human on the sofa. Purring level: maximum.',999),
    ('Midnight Mischief', 'Knocked over a vase during a midnight exploration of the kitchen counters.',999),
    ('Feather Toy Frenzy', 'Spent an hour trying to catch the feather toy. Almost got it!',999),
    ('Window Birdwatching', 'Saw a blue jay today. New bird friend? Still not sure.',999),
    ('The Great Escape', 'Attempted to slip through the door. Foiled by quick human reflexes.',999),
    ('Midday Meditation', 'Sat perfectly still for 15 minutes, staring at the wall. Deep thoughts.',999),
    ('Laundry Basket Hideout', 'Discovered the laundry basket makes an excellent hiding spot. Cozy!',999),
    ('Curtain Climbing', 'Tried climbing the curtains. Got stuck halfway. Called for backup.',999),
    ('The Mysterious Shadow', 'Chased a mysterious shadow across the room. It disappeared!',999),
    ('Cardboard Castle', 'Found an empty box and claimed it as my new castle. Defended it fiercely.',999),
    ('Snack Time Sabotage', 'Knocked over the treat jar. Humans were not amused.',999),
    ('The Bath Incident', 'Accidentally fell into the bathtub. A soggy but enlightening experience.',999);
